# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created: Wed Aug 20 19:14:01 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(747, 477)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 6, 2, 1)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_choose = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_choose.sizePolicy().hasHeightForWidth())
        self.btn_choose.setSizePolicy(sizePolicy)
        self.btn_choose.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_choose.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_choose.setFont(font)
        self.btn_choose.setObjectName(_fromUtf8("btn_choose"))
        self.gridLayout.addWidget(self.btn_choose, 1, 0, 1, 1)
        self.line_info = QtGui.QLineEdit(self.centralwidget)
        self.line_info.setMinimumSize(QtCore.QSize(0, 30))
        self.line_info.setObjectName(_fromUtf8("line_info"))
        self.gridLayout.addWidget(self.line_info, 1, 1, 1, 2)
        self.list_file = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_file.sizePolicy().hasHeightForWidth())
        self.list_file.setSizePolicy(sizePolicy)
        self.list_file.setMinimumSize(QtCore.QSize(170, 0))
        self.list_file.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_file.setFont(font)
        self.list_file.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.list_file.setStyleSheet(_fromUtf8(""))
        self.list_file.setFrameShape(QtGui.QFrame.StyledPanel)
        self.list_file.setFrameShadow(QtGui.QFrame.Sunken)
        self.list_file.setResizeMode(QtGui.QListView.Adjust)
        self.list_file.setGridSize(QtCore.QSize(10, 20))
        self.list_file.setViewMode(QtGui.QListView.ListMode)
        self.list_file.setModelColumn(0)
        self.list_file.setObjectName(_fromUtf8("list_file"))
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.Dense3Pattern)
        item.setForeground(brush)
        self.list_file.addItem(item)
        self.gridLayout.addWidget(self.list_file, 2, 0, 1, 1)
        self.table = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setFrameShadow(QtGui.QFrame.Sunken)
        self.table.setDragEnabled(True)
        self.table.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.table.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.table.setAlternatingRowColors(False)
        self.table.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(5)
        self.table.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 167, 167))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        self.table.setItem(0, 0, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(100)
        self.table.horizontalHeader().setMinimumSectionSize(30)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout.addWidget(self.table, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.list_file, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), self.table.resizeRowsToContents)
        QtCore.QObject.connect(self.list_file, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), self.table.setFocus)
        QtCore.QObject.connect(self.list_file, QtCore.SIGNAL(_fromUtf8("itemActivated(QListWidgetItem*)")), self.table.resizeColumnsToContents)
        QtCore.QObject.connect(self.list_file, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), self.table.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.btn_choose.setText(_translate("MainWindow", "Choose Folder or Drop file here -->", None))
        self.list_file.setSortingEnabled(False)
        __sortingEnabled = self.list_file.isSortingEnabled()
        self.list_file.setSortingEnabled(False)
        item = self.list_file.item(0)
        item.setText(_translate("MainWindow", "Summary", None))
        self.list_file.setSortingEnabled(__sortingEnabled)
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12", None))
        item = self.table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13", None))
        item = self.table.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Test name", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fingerprint", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Test Start date", None))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Test End date", None))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Failed", None))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        item = self.table.item(0, 0)
        item.setText(_translate("MainWindow", " ", None))
        self.table.setSortingEnabled(__sortingEnabled)

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created: Wed Aug 20 19:17:11 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(747, 477)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(2, 6, 2, 1)
        self.gridLayout.setHorizontalSpacing(2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_choose = QtGui.QPushButton(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_choose.sizePolicy().hasHeightForWidth())
        self.btn_choose.setSizePolicy(sizePolicy)
        self.btn_choose.setMinimumSize(QtCore.QSize(0, 30))
        self.btn_choose.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_choose.setFont(font)
        self.btn_choose.setObjectName(_fromUtf8("btn_choose"))
        self.gridLayout.addWidget(self.btn_choose, 1, 0, 1, 1)
        self.line_info = QtGui.QLineEdit(self.centralwidget)
        self.line_info.setMinimumSize(QtCore.QSize(0, 30))
        self.line_info.setObjectName(_fromUtf8("line_info"))
        self.gridLayout.addWidget(self.line_info, 1, 1, 1, 2)
        self.list_file = QtGui.QListWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_file.sizePolicy().hasHeightForWidth())
        self.list_file.setSizePolicy(sizePolicy)
        self.list_file.setMinimumSize(QtCore.QSize(170, 0))
        self.list_file.setMaximumSize(QtCore.QSize(220, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.list_file.setFont(font)
        self.list_file.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.list_file.setStyleSheet(_fromUtf8(""))
        self.list_file.setFrameShape(QtGui.QFrame.StyledPanel)
        self.list_file.setFrameShadow(QtGui.QFrame.Sunken)
        self.list_file.setResizeMode(QtGui.QListView.Adjust)
        self.list_file.setGridSize(QtCore.QSize(10, 20))
        self.list_file.setViewMode(QtGui.QListView.ListMode)
        self.list_file.setModelColumn(0)
        self.list_file.setObjectName(_fromUtf8("list_file"))
        item = QtGui.QListWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 127))
        brush.setStyle(QtCore.Qt.Dense3Pattern)
        item.setForeground(brush)
        self.list_file.addItem(item)
        self.gridLayout.addWidget(self.list_file, 2, 0, 1, 1)
        self.table = QtGui.QTableWidget(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setFrameShadow(QtGui.QFrame.Sunken)
        self.table.setDragEnabled(True)
        self.table.setDragDropMode(QtGui.QAbstractItemView.DragDrop)
        self.table.setDefaultDropAction(QtCore.Qt.LinkAction)
        self.table.setAlternatingRowColors(False)
        self.table.setSelectionBehavior(QtGui.QAbstractItemView.SelectItems)
        self.table.setObjectName(_fromUtf8("table"))
        self.table.setColumnCount(5)
        self.table.setRowCount(14)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(9, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(10, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(11, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(12, item)
        item = QtGui.QTableWidgetItem()
        self.table.setVerticalHeaderItem(13, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.table.setItem(0, 0, item)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(100)
        self.table.horizontalHeader().setMinimumSectionSize(30)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout.addWidget(self.table, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.list_file, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), self.table.resizeRowsToContents)
        QtCore.QObject.connect(self.list_file, QtCore.SIGNAL(_fromUtf8("itemClicked(QListWidgetItem*)")), self.table.setFocus)
        QtCore.QObject.connect(self.list_file, QtCore.SIGNAL(_fromUtf8("itemActivated(QListWidgetItem*)")), self.table.resizeColumnsToContents)
        QtCore.QObject.connect(self.list_file, QtCore.SIGNAL(_fromUtf8("clicked(QModelIndex)")), self.table.update)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.btn_choose.setText(_translate("MainWindow", "Choose Folder or Drop file here -->", None))
        self.list_file.setSortingEnabled(False)
        __sortingEnabled = self.list_file.isSortingEnabled()
        self.list_file.setSortingEnabled(False)
        item = self.list_file.item(0)
        item.setText(_translate("MainWindow", "Summary", None))
        self.list_file.setSortingEnabled(__sortingEnabled)
        item = self.table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1", None))
        item = self.table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2", None))
        item = self.table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3", None))
        item = self.table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4", None))
        item = self.table.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5", None))
        item = self.table.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6", None))
        item = self.table.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7", None))
        item = self.table.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8", None))
        item = self.table.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9", None))
        item = self.table.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "10", None))
        item = self.table.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "11", None))
        item = self.table.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "12", None))
        item = self.table.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "13", None))
        item = self.table.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "14", None))
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Test name", None))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fingerprint", None))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Test Start date", None))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Test End date", None))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Failed", None))
        __sortingEnabled = self.table.isSortingEnabled()
        self.table.setSortingEnabled(False)
        item = self.table.item(0, 0)
        item.setText(_translate("MainWindow", " ", None))
        self.table.setSortingEnabled(__sortingEnabled)

