# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Mainwindow.ui'
#
# Created: Wed Oct 08 13:41:50 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(318, 398)
        MainWindow.setMinimumSize(QtCore.QSize(160, 0))
        MainWindow.setMaximumSize(QtCore.QSize(533, 16777215))
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setBaseSize(QtCore.QSize(240, 380))
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(217, 233, 255);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_2.setMargin(2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(230, 240, 255);"))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_1 = QtGui.QWidget()
        self.tab_1.setObjectName(_fromUtf8("tab_1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_1)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setSpacing(1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setContentsMargins(1, 3, 1, 2)
        self.gridLayout_7.setHorizontalSpacing(2)
        self.gridLayout_7.setVerticalSpacing(5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.toolBox_3 = QtGui.QToolBox(self.tab_1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox_3.sizePolicy().hasHeightForWidth())
        self.toolBox_3.setSizePolicy(sizePolicy)
        self.toolBox_3.setMinimumSize(QtCore.QSize(0, 265))
        self.toolBox_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.toolBox_3.setFrameShadow(QtGui.QFrame.Raised)
        self.toolBox_3.setLineWidth(1)
        self.toolBox_3.setObjectName(_fromUtf8("toolBox_3"))
        self.page_5 = QtGui.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 304, 217))
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_9.setContentsMargins(1, 1, 1, 2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.list_size = QtGui.QListWidget(self.page_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_size.sizePolicy().hasHeightForWidth())
        self.list_size.setSizePolicy(sizePolicy)
        self.list_size.setMinimumSize(QtCore.QSize(0, 40))
        self.list_size.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.list_size.setAcceptDrops(True)
        self.list_size.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 143);"))
        self.list_size.setFrameShape(QtGui.QFrame.WinPanel)
        self.list_size.setFrameShadow(QtGui.QFrame.Sunken)
        self.list_size.setMidLineWidth(1)
        self.list_size.setObjectName(_fromUtf8("list_size"))
        item = QtGui.QListWidgetItem()
        self.list_size.addItem(item)
        self.gridLayout_9.addWidget(self.list_size, 0, 0, 1, 1)
        self.toolBox_3.addItem(self.page_5, _fromUtf8(""))
        self.page_6 = QtGui.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 304, 217))
        self.page_6.setObjectName(_fromUtf8("page_6"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_6)
        self.gridLayout_8.setContentsMargins(1, 1, 1, 2)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.list_mail = QtGui.QListWidget(self.page_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.list_mail.sizePolicy().hasHeightForWidth())
        self.list_mail.setSizePolicy(sizePolicy)
        self.list_mail.setMinimumSize(QtCore.QSize(0, 150))
        self.list_mail.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.list_mail.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.list_mail.setAcceptDrops(True)
        self.list_mail.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 143);"))
        self.list_mail.setFrameShape(QtGui.QFrame.WinPanel)
        self.list_mail.setFrameShadow(QtGui.QFrame.Sunken)
        self.list_mail.setObjectName(_fromUtf8("list_mail"))
        item = QtGui.QListWidgetItem()
        self.list_mail.addItem(item)
        self.gridLayout_8.addWidget(self.list_mail, 0, 0, 1, 1)
        self.toolBox_3.addItem(self.page_6, _fromUtf8(""))
        self.gridLayout_7.addWidget(self.toolBox_3, 3, 0, 1, 1)
        self.label_0 = QtGui.QLabel(self.tab_1)
        self.label_0.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_0.sizePolicy().hasHeightForWidth())
        self.label_0.setSizePolicy(sizePolicy)
        self.label_0.setMinimumSize(QtCore.QSize(0, 30))
        self.label_0.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_0.setFont(font)
        self.label_0.setObjectName(_fromUtf8("label_0"))
        self.gridLayout_7.addWidget(self.label_0, 1, 0, 1, 1)
        self.line_info = QtGui.QLineEdit(self.tab_1)
        self.line_info.setMinimumSize(QtCore.QSize(30, 30))
        self.line_info.setMaximumSize(QtCore.QSize(16777215, 30))
        self.line_info.setAcceptDrops(True)
        self.line_info.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.line_info.setInputMethodHints(QtCore.Qt.ImhNone)
        self.line_info.setText(_fromUtf8(""))
        self.line_info.setDragEnabled(True)
        self.line_info.setObjectName(_fromUtf8("line_info"))
        self.gridLayout_7.addWidget(self.line_info, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_1, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_10.setContentsMargins(2, 3, 2, 2)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_name = QtGui.QPlainTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(15)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setMinimumSize(QtCore.QSize(0, 18))
        self.label_name.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_name.setToolTip(_fromUtf8(""))
        self.label_name.setStatusTip(_fromUtf8(""))
        self.label_name.setWhatsThis(_fromUtf8(""))
        self.label_name.setAccessibleDescription(_fromUtf8(""))
        self.label_name.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.label_name.setFrameShape(QtGui.QFrame.Panel)
        self.label_name.setMidLineWidth(1)
        self.label_name.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_name.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.label_name.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.label_name.setPlainText(_fromUtf8(""))
        self.label_name.setObjectName(_fromUtf8("label_name"))
        self.gridLayout_10.addWidget(self.label_name, 11, 1, 1, 1)
        self.line_csc = QtGui.QLineEdit(self.tab_2)
        self.line_csc.setEnabled(True)
        self.line_csc.setToolTip(_fromUtf8(""))
        self.line_csc.setAutoFillBackground(False)
        self.line_csc.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_csc.setDragEnabled(True)
        self.line_csc.setObjectName(_fromUtf8("line_csc"))
        self.gridLayout_10.addWidget(self.line_csc, 3, 1, 1, 1)
        self.line_p4port = QtGui.QLineEdit(self.tab_2)
        self.line_p4port.setToolTip(_fromUtf8(""))
        self.line_p4port.setAutoFillBackground(False)
        self.line_p4port.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_p4port.setDragEnabled(True)
        self.line_p4port.setObjectName(_fromUtf8("line_p4port"))
        self.gridLayout_10.addWidget(self.line_p4port, 10, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab_2)
        self.label_12.setMinimumSize(QtCore.QSize(60, 0))
        self.label_12.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_12.setMouseTracking(False)
        self.label_12.setToolTip(_fromUtf8(""))
        self.label_12.setAutoFillBackground(False)
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(0, 0, 127);"))
        self.label_12.setFrameShape(QtGui.QFrame.Box)
        self.label_12.setFrameShadow(QtGui.QFrame.Raised)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_10.addWidget(self.label_12, 11, 0, 1, 1)
        self.line_partial = QtGui.QPlainTextEdit(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.line_partial.sizePolicy().hasHeightForWidth())
        self.line_partial.setSizePolicy(sizePolicy)
        self.line_partial.setMinimumSize(QtCore.QSize(0, 18))
        self.line_partial.setBaseSize(QtCore.QSize(0, 8))
        self.line_partial.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_partial.setFrameShape(QtGui.QFrame.Panel)
        self.line_partial.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_partial.setLineWidth(1)
        self.line_partial.setMidLineWidth(1)
        self.line_partial.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.line_partial.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.line_partial.setBackgroundVisible(True)
        self.line_partial.setObjectName(_fromUtf8("line_partial"))
        self.gridLayout_10.addWidget(self.line_partial, 8, 1, 1, 1)
        self.line_modem = QtGui.QLineEdit(self.tab_2)
        self.line_modem.setToolTip(_fromUtf8(""))
        self.line_modem.setAutoFillBackground(False)
        self.line_modem.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_modem.setDragEnabled(True)
        self.line_modem.setObjectName(_fromUtf8("line_modem"))
        self.gridLayout_10.addWidget(self.line_modem, 4, 1, 1, 1)
        self.line_approver = QtGui.QLineEdit(self.tab_2)
        self.line_approver.setToolTip(_fromUtf8(""))
        self.line_approver.setAutoFillBackground(False)
        self.line_approver.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_approver.setDragEnabled(True)
        self.line_approver.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.line_approver.setObjectName(_fromUtf8("line_approver"))
        self.gridLayout_10.addWidget(self.line_approver, 9, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.tab_2)
        self.label_5.setMinimumSize(QtCore.QSize(60, 0))
        self.label_5.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_5.setMouseTracking(False)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_5.setFrameShape(QtGui.QFrame.Box)
        self.label_5.setFrameShadow(QtGui.QFrame.Raised)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_10.addWidget(self.label_5, 4, 0, 1, 1)
        self.line_full = QtGui.QLineEdit(self.tab_2)
        self.line_full.setToolTip(_fromUtf8(""))
        self.line_full.setAutoFillBackground(False)
        self.line_full.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_full.setDragEnabled(True)
        self.line_full.setObjectName(_fromUtf8("line_full"))
        self.gridLayout_10.addWidget(self.line_full, 7, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab_2)
        self.label_6.setMinimumSize(QtCore.QSize(60, 0))
        self.label_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_6.setFrameShape(QtGui.QFrame.Box)
        self.label_6.setFrameShadow(QtGui.QFrame.Raised)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_10.addWidget(self.label_6, 5, 0, 1, 1)
        self.line_template = QtGui.QLineEdit(self.tab_2)
        self.line_template.setToolTip(_fromUtf8(""))
        self.line_template.setAutoFillBackground(False)
        self.line_template.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_template.setDragEnabled(True)
        self.line_template.setObjectName(_fromUtf8("line_template"))
        self.gridLayout_10.addWidget(self.line_template, 6, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab_2)
        self.label_11.setMinimumSize(QtCore.QSize(60, 0))
        self.label_11.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_11.setFrameShape(QtGui.QFrame.Box)
        self.label_11.setFrameShadow(QtGui.QFrame.Raised)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_10.addWidget(self.label_11, 10, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_7.setFrameShape(QtGui.QFrame.Box)
        self.label_7.setFrameShadow(QtGui.QFrame.Raised)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_10.addWidget(self.label_7, 6, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab_2)
        self.label_9.setMinimumSize(QtCore.QSize(60, 0))
        self.label_9.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_9.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_9.setFrameShape(QtGui.QFrame.Box)
        self.label_9.setFrameShadow(QtGui.QFrame.Raised)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 8, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab_2)
        self.label_10.setMinimumSize(QtCore.QSize(60, 0))
        self.label_10.setMaximumSize(QtCore.QSize(60, 200))
        self.label_10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_10.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_10.setFrameShape(QtGui.QFrame.Box)
        self.label_10.setFrameShadow(QtGui.QFrame.Raised)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_10.addWidget(self.label_10, 9, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab_2)
        self.label_8.setMinimumSize(QtCore.QSize(60, 0))
        self.label_8.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_8.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_8.setFrameShape(QtGui.QFrame.Box)
        self.label_8.setFrameShadow(QtGui.QFrame.Raised)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_10.addWidget(self.label_8, 7, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 12, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setMinimumSize(QtCore.QSize(60, 0))
        self.label_4.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_4.setMouseTracking(False)
        self.label_4.setAutoFillBackground(False)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_4.setFrameShape(QtGui.QFrame.Box)
        self.label_4.setFrameShadow(QtGui.QFrame.Raised)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_10.addWidget(self.label_4, 3, 0, 1, 1)
        self.comboBox = QtGui.QComboBox(self.tab_2)
        self.comboBox.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.gridLayout_10.addWidget(self.comboBox, 5, 1, 1, 1)
        self.line_code = QtGui.QLineEdit(self.tab_2)
        self.line_code.setToolTip(_fromUtf8(""))
        self.line_code.setAutoFillBackground(False)
        self.line_code.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_code.setDragEnabled(True)
        self.line_code.setObjectName(_fromUtf8("line_code"))
        self.gridLayout_10.addWidget(self.line_code, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setMinimumSize(QtCore.QSize(60, 0))
        self.label_3.setMaximumSize(QtCore.QSize(60, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_3.setMouseTracking(False)
        self.label_3.setAutoFillBackground(False)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_3.setFrameShape(QtGui.QFrame.Box)
        self.label_3.setFrameShadow(QtGui.QFrame.Raised)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_10.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setMinimumSize(QtCore.QSize(60, 0))
        self.label_2.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_2.setToolTip(_fromUtf8(""))
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_2.setFrameShape(QtGui.QFrame.Box)
        self.label_2.setFrameShadow(QtGui.QFrame.Raised)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_10.addWidget(self.label_2, 1, 0, 1, 1)
        self.line_project = QtGui.QLineEdit(self.tab_2)
        self.line_project.setToolTip(_fromUtf8(""))
        self.line_project.setAutoFillBackground(False)
        self.line_project.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_project.setDragEnabled(True)
        self.line_project.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.line_project.setObjectName(_fromUtf8("line_project"))
        self.gridLayout_10.addWidget(self.line_project, 0, 1, 1, 1)
        self.line_date = QtGui.QLineEdit(self.tab_2)
        self.line_date.setToolTip(_fromUtf8(""))
        self.line_date.setAutoFillBackground(False)
        self.line_date.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_date.setDragEnabled(True)
        self.line_date.setObjectName(_fromUtf8("line_date"))
        self.gridLayout_10.addWidget(self.line_date, 1, 1, 1, 1)
        self.label_1 = QtGui.QLabel(self.tab_2)
        self.label_1.setMinimumSize(QtCore.QSize(60, 0))
        self.label_1.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_1.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_1.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.label_1.setFrameShape(QtGui.QFrame.Box)
        self.label_1.setFrameShadow(QtGui.QFrame.Raised)
        self.label_1.setTextFormat(QtCore.Qt.PlainText)
        self.label_1.setOpenExternalLinks(True)
        self.label_1.setObjectName(_fromUtf8("label_1"))
        self.gridLayout_10.addWidget(self.label_1, 0, 0, 1, 1)
        self.btn_clean = QtGui.QPushButton(self.tab_2)
        self.btn_clean.setMinimumSize(QtCore.QSize(55, 30))
        self.btn_clean.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clean.setFont(font)
        self.btn_clean.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_clean.setToolTip(_fromUtf8(""))
        self.btn_clean.setStatusTip(_fromUtf8(""))
        self.btn_clean.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));"))
        self.btn_clean.setCheckable(False)
        self.btn_clean.setDefault(False)
        self.btn_clean.setFlat(False)
        self.btn_clean.setObjectName(_fromUtf8("btn_clean"))
        self.gridLayout_10.addWidget(self.btn_clean, 13, 0, 1, 1)
        self.btn_label = QtGui.QPushButton(self.tab_2)
        self.btn_label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.btn_label.setFont(font)
        self.btn_label.setAutoFillBackground(False)
        self.btn_label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 178, 102, 255), stop:0.55 rgba(235, 148, 61, 255), stop:0.98 rgba(0, 0, 0, 255), stop:1 rgba(0, 0, 0, 0));"))
        self.btn_label.setObjectName(_fromUtf8("btn_label"))
        self.gridLayout_10.addWidget(self.btn_label, 13, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_11 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_11.setContentsMargins(2, 2, 1, 1)
        self.gridLayout_11.setHorizontalSpacing(1)
        self.gridLayout_11.setVerticalSpacing(2)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.line_smd_home = QtGui.QPlainTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_smd_home.sizePolicy().hasHeightForWidth())
        self.line_smd_home.setSizePolicy(sizePolicy)
        self.line_smd_home.setMinimumSize(QtCore.QSize(0, 20))
        self.line_smd_home.setBaseSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_smd_home.setFont(font)
        self.line_smd_home.setFrameShape(QtGui.QFrame.Panel)
        self.line_smd_home.setMidLineWidth(1)
        self.line_smd_home.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.line_smd_home.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.line_smd_home.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.line_smd_home.setPlainText(_fromUtf8(""))
        self.line_smd_home.setObjectName(_fromUtf8("line_smd_home"))
        self.gridLayout_11.addWidget(self.line_smd_home, 3, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem1, 14, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_16.setFrameShape(QtGui.QFrame.Box)
        self.label_16.setFrameShadow(QtGui.QFrame.Raised)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_11.addWidget(self.label_16, 10, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_13.setFrameShape(QtGui.QFrame.Box)
        self.label_13.setFrameShadow(QtGui.QFrame.Raised)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_11.addWidget(self.label_13, 0, 0, 1, 1)
        self.line_manager = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_manager.sizePolicy().hasHeightForWidth())
        self.line_manager.setSizePolicy(sizePolicy)
        self.line_manager.setMinimumSize(QtCore.QSize(218, 20))
        self.line_manager.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_manager.setText(_fromUtf8(""))
        self.line_manager.setFrame(True)
        self.line_manager.setDragEnabled(True)
        self.line_manager.setObjectName(_fromUtf8("line_manager"))
        self.gridLayout_11.addWidget(self.line_manager, 11, 0, 1, 1)
        self.line_user = QtGui.QLineEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_user.sizePolicy().hasHeightForWidth())
        self.line_user.setSizePolicy(sizePolicy)
        self.line_user.setMinimumSize(QtCore.QSize(218, 20))
        self.line_user.setStyleSheet(_fromUtf8("color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);"))
        self.line_user.setText(_fromUtf8(""))
        self.line_user.setFrame(True)
        self.line_user.setDragEnabled(True)
        self.line_user.setObjectName(_fromUtf8("line_user"))
        self.gridLayout_11.addWidget(self.line_user, 9, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_14.setFrameShape(QtGui.QFrame.Box)
        self.label_14.setFrameShadow(QtGui.QFrame.Raised)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_11.addWidget(self.label_14, 2, 0, 1, 1)
        self.line_smd = QtGui.QPlainTextEdit(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_smd.sizePolicy().hasHeightForWidth())
        self.line_smd.setSizePolicy(sizePolicy)
        self.line_smd.setMinimumSize(QtCore.QSize(0, 20))
        self.line_smd.setBaseSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.line_smd.setFont(font)
        self.line_smd.setFrameShape(QtGui.QFrame.Panel)
        self.line_smd.setMidLineWidth(1)
        self.line_smd.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.line_smd.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.line_smd.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.line_smd.setPlainText(_fromUtf8(""))
        self.line_smd.setObjectName(_fromUtf8("line_smd"))
        self.gridLayout_11.addWidget(self.line_smd, 1, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_15.setFrameShape(QtGui.QFrame.Box)
        self.label_15.setFrameShadow(QtGui.QFrame.Raised)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_11.addWidget(self.label_15, 4, 0, 1, 1)
        self.calendarWidget = QtGui.QCalendarWidget(self.tab_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calendarWidget.sizePolicy().hasHeightForWidth())
        self.calendarWidget.setSizePolicy(sizePolicy)
        self.calendarWidget.setStyleSheet(_fromUtf8("color: rgb(0, 0, 143);"))
        self.calendarWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.calendarWidget.setGridVisible(True)
        self.calendarWidget.setSelectionMode(QtGui.QCalendarWidget.NoSelection)
        self.calendarWidget.setHorizontalHeaderFormat(QtGui.QCalendarWidget.LongDayNames)
        self.calendarWidget.setVerticalHeaderFormat(QtGui.QCalendarWidget.ISOWeekNumbers)
        self.calendarWidget.setNavigationBarVisible(True)
        self.calendarWidget.setDateEditEnabled(False)
        self.calendarWidget.setObjectName(_fromUtf8("calendarWidget"))
        self.gridLayout_11.addWidget(self.calendarWidget, 13, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox_3.setCurrentIndex(1)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_p4port.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_approver.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_full.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_template.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_modem.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_csc.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_code.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_project.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.list_mail.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.list_size.clear)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), self.line_template.clear)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), self.line_full.clear)
        QtCore.QObject.connect(self.comboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(QString)")), self.line_p4port.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_info.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_partial.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_manager.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_user.clear)
        QtCore.QObject.connect(self.label_name, QtCore.SIGNAL(_fromUtf8("textChanged()")), self.tabWidget.showMaximized)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_smd.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.line_smd_home.clear)
        QtCore.QObject.connect(self.btn_clean, QtCore.SIGNAL(_fromUtf8("clicked()")), self.label_name.clear)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.line_info)
        MainWindow.setTabOrder(self.line_info, self.list_size)
        MainWindow.setTabOrder(self.list_size, self.list_mail)
        MainWindow.setTabOrder(self.list_mail, self.line_project)
        MainWindow.setTabOrder(self.line_project, self.line_date)
        MainWindow.setTabOrder(self.line_date, self.line_code)
        MainWindow.setTabOrder(self.line_code, self.line_csc)
        MainWindow.setTabOrder(self.line_csc, self.line_modem)
        MainWindow.setTabOrder(self.line_modem, self.comboBox)
        MainWindow.setTabOrder(self.comboBox, self.line_template)
        MainWindow.setTabOrder(self.line_template, self.line_full)
        MainWindow.setTabOrder(self.line_full, self.line_partial)
        MainWindow.setTabOrder(self.line_partial, self.line_approver)
        MainWindow.setTabOrder(self.line_approver, self.line_p4port)
        MainWindow.setTabOrder(self.line_p4port, self.label_name)
        MainWindow.setTabOrder(self.label_name, self.btn_clean)
        MainWindow.setTabOrder(self.btn_clean, self.btn_label)
        MainWindow.setTabOrder(self.btn_label, self.line_smd)
        MainWindow.setTabOrder(self.line_smd, self.line_smd_home)
        MainWindow.setTabOrder(self.line_smd_home, self.line_user)
        MainWindow.setTabOrder(self.line_user, self.line_manager)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RT Help Box", None))
        self.toolBox_3.setStatusTip(_translate("MainWindow", "Press Enter in Drag & Drop field for clean only this Tab", None))
        self.list_size.setSortingEnabled(False)
        __sortingEnabled = self.list_size.isSortingEnabled()
        self.list_size.setSortingEnabled(False)
        item = self.list_size.item(0)
        item.setText(_translate("MainWindow", "Select all", None))
        self.list_size.setSortingEnabled(__sortingEnabled)
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_5), _translate("MainWindow", "Binary Size", None))
        self.list_mail.setStatusTip(_translate("MainWindow", "There are no Group names present in this list!!!", None))
        __sortingEnabled = self.list_mail.isSortingEnabled()
        self.list_mail.setSortingEnabled(False)
        item = self.list_mail.item(0)
        item.setText(_translate("MainWindow", "Select all", None))
        self.list_mail.setSortingEnabled(__sortingEnabled)
        self.toolBox_3.setItemText(self.toolBox_3.indexOf(self.page_6), _translate("MainWindow", "Mail List", None))
        self.label_0.setText(_translate("MainWindow", " Drag & Drop files or info here:", None))
        self.line_info.setStatusTip(_translate("MainWindow", "Drag & Drop SE selected data into  this field only!!!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "Size/Mail", None))
        self.label_12.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_12.setText(_translate("MainWindow", "Label", None))
        self.label_5.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_5.setText(_translate("MainWindow", "Modem", None))
        self.label_6.setText(_translate("MainWindow", "Bin Type", None))
        self.label_11.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_11.setText(_translate("MainWindow", "P4 Port", None))
        self.label_7.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_7.setText(_translate("MainWindow", "Template", None))
        self.label_9.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_9.setText(_translate("MainWindow", "Cl Partials", None))
        self.label_10.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_10.setText(_translate("MainWindow", "PL member", None))
        self.label_8.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_8.setText(_translate("MainWindow", "Cl Full", None))
        self.label_4.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_4.setText(_translate("MainWindow", "CSC", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "CSC", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "CODE", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "MODEM", None))
        self.label_3.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_3.setText(_translate("MainWindow", "Code", None))
        self.label_2.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_2.setText(_translate("MainWindow", "Date", None))
        self.label_1.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_1.setText(_translate("MainWindow", "Project", None))
        self.btn_clean.setText(_translate("MainWindow", "Clean", None))
        self.btn_label.setText(_translate("MainWindow", "Labeling Tool", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Release Info", None))
        self.line_smd_home.setStyleSheet(_translate("MainWindow", "color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);", None))
        self.label_16.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_16.setText(_translate("MainWindow", "Project Manager", None))
        self.label_13.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_13.setText(_translate("MainWindow", "CODE_CSC_MODEM ", None))
        self.label_14.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_14.setText(_translate("MainWindow", "CODE_CSC_MODEM_HOME", None))
        self.line_smd.setStyleSheet(_translate("MainWindow", "color: rgb(0, 0, 95);\n"
"background-color: rgb(255, 255, 255);\n"
"selection-color: rgb(0, 0, 143);\n"
"selection-background-color: rgb(161, 211, 255);", None))
        self.label_15.setStatusTip(_translate("MainWindow", "Click for copying!", None))
        self.label_15.setText(_translate("MainWindow", "Approval User", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "SMD Info", None))

